'use strict';

module.exports = {
  es: {
    translation: {
      Spell: {
        LaunchFirstTime: 'Hola {{name}}! Ya que esta es la primera vez que juegas con Avada Kedavra, ' +
          'permíteme explicarte lo que podemos hacer. Primero que todo, no vamos a matar a nadie con un ' +
          'hechizo, pero te puedo asegurar que nos divertiremos con los sonidos hechos con nuestros ' +
          'encantamientos. Así que empecemos de una vez.',
        Launch: 'Hola de nuevo {{name}}. Aquí vamos.',
        Next: 'Okey',
        Previous: 'Okey, este es el hechizo anterior',
        StartOver: 'Okey',
        Unhandled: 'Lo siento, no entendí lo que dijiste, tal vez fue un hechizo nuevo que no conozco? ' +
          'Apuesto que no conoces este tampoco',
        reprompt: [
          '¿Continuamos?',
          '¿Seguimos?',
          '¿Te gustaría seguir?',
          '¿Te gustaría seguir practicando?',
        ],

        CardTitle: 'Práctica de Hechizo',
      },

      Help: {
        ask: 'Me encantan todos los hechizos, maldiciones y encantamientos, pero algunas veces my varita mágica no funciona como espero. ' +
          'No importa, puedo ayudarte a practicar tus hechizos, mi especialidad es el adavra kedabra, pero no te preocupes, ' +
          'no puedo matar ni a una mosca. Entonces, ¿quieres practicar algunos hechizos conmigo?',
        reprompt: '¿Quieres practicar algunos hechizos?',
      },

      Exit: 'Adiós, y gracias por practicar. Hasta la próxima!',

      SuggestionChips: [
        'si',
        'no',
      ],

      Interjections: [
        '<say-as interpret-as="interjection"> abracadabra </say-as>',
        '<say-as interpret-as="interjection"> aggggh </say-as>',
        '<say-as interpret-as="interjection"> ah </say-as>',
        '<say-as interpret-as="interjection"> ahí va </say-as>',
        '<say-as interpret-as="interjection"> argh </say-as>',
        '<say-as interpret-as="interjection"> au! </say-as>',
        '<say-as interpret-as="interjection"> auch </say-as>',
        '<say-as interpret-as="interjection"> ay </say-as>',
        '<say-as interpret-as="interjection"> ay ay ay </say-as>',
        '<say-as interpret-as="interjection"> ay de mí </say-as>',
        '<say-as interpret-as="interjection"> badabim badabum </say-as>',
        '<say-as interpret-as="interjection"> badabum </say-as>',
        '<say-as interpret-as="interjection"> bang </say-as>',
        '<say-as interpret-as="interjection"> bang bang </say-as>',
        '<say-as interpret-as="interjection"> bazinga </say-as>',
        '<say-as interpret-as="interjection"> bingo </say-as>',
        '<say-as interpret-as="interjection"> boing </say-as>',
        '<say-as interpret-as="interjection"> boom </say-as>',
        '<say-as interpret-as="interjection"> booya </say-as>',
        '<say-as interpret-as="interjection"> bravo </say-as>',
        '<say-as interpret-as="interjection"> bueno </say-as>',
        '<say-as interpret-as="interjection"> buu </say-as>',
        '<say-as interpret-as="interjection"> buuu buuu </say-as>',
        '<say-as interpret-as="interjection"> caracoles </say-as>',
        '<say-as interpret-as="interjection"> caramba </say-as>',
        '<say-as interpret-as="interjection"> caray </say-as>',
        '<say-as interpret-as="interjection"> catapúm </say-as>',
        '<say-as interpret-as="interjection"> chas </say-as>',
        '<say-as interpret-as="interjection"> chissst chsss </say-as>',
        '<say-as interpret-as="interjection"> chist </say-as>',
        '<say-as interpret-as="interjection"> choca esos cinco </say-as>',
        '<say-as interpret-as="interjection"> chuu chuu </say-as>',
        '<say-as interpret-as="interjection"> cielo santo </say-as>',
        '<say-as interpret-as="interjection"> cielos </say-as>',
        '<say-as interpret-as="interjection"> cuidado </say-as>',
        '<say-as interpret-as="interjection"> cáspita </say-as>',
        '<say-as interpret-as="interjection"> diablos </say-as>',
        '<say-as interpret-as="interjection"> dios mío </say-as>',
        '<say-as interpret-as="interjection"> dios santo </say-as>',
        '<say-as interpret-as="interjection"> estupendo </say-as>',
        '<say-as interpret-as="interjection"> eureka </say-as>',
        '<say-as interpret-as="interjection"> excelente </say-as>',
        '<say-as interpret-as="interjection"> genial </say-as>',
        '<say-as interpret-as="interjection"> guau </say-as>',
        '<say-as interpret-as="interjection"> hala </say-as>',
        '<say-as interpret-as="interjection"> ja </say-as>',
        '<say-as interpret-as="interjection"> ja ja </say-as>',
        '<say-as interpret-as="interjection"> jajaja </say-as>',
        '<say-as interpret-as="interjection"> jejeje </say-as>',
        '<say-as interpret-as="interjection"> jijiji </say-as>',
        '<say-as interpret-as="interjection"> jojojo </say-as>',
        '<say-as interpret-as="interjection"> kabúm </say-as>',
        '<say-as interpret-as="interjection"> madre mía </say-as>',
        '<say-as interpret-as="interjection"> magnífico </say-as>',
        '<say-as interpret-as="interjection"> mamma mia </say-as>',
        '<say-as interpret-as="interjection"> mi madre </say-as>',
        '<say-as interpret-as="interjection"> nooo </say-as>',
        '<say-as interpret-as="interjection"> oh no </say-as>',
        '<say-as interpret-as="interjection"> oh sí </say-as>',
        '<say-as interpret-as="interjection"> oh yeah </say-as>',
        '<say-as interpret-as="interjection"> oh yes </say-as>',
        '<say-as interpret-as="interjection"> oooh </say-as>',
        '<say-as interpret-as="interjection"> pium pium </say-as>',
        '<say-as interpret-as="interjection"> pss </say-as>',
        '<say-as interpret-as="interjection"> rayos </say-as>',
        '<say-as interpret-as="interjection"> recórcholis </say-as>',
        '<say-as interpret-as="interjection"> toma </say-as>',
        '<say-as interpret-as="interjection"> tralalalá </say-as>',
        '<say-as interpret-as="interjection"> uf </say-as>',
        '<say-as interpret-as="interjection"> uups </say-as>',
        '<say-as interpret-as="interjection"> yabadabadu </say-as>',
        '<say-as interpret-as="interjection"> yiii jaa </say-as>',
        '<say-as interpret-as="interjection"> yuhuu </say-as>',
        '<say-as interpret-as="interjection"> yupi </say-as>',
        '<say-as interpret-as="interjection"> zas </say-as>',
        '<say-as interpret-as="interjection"> zas en toda la boca </say-as>',
      ],

      AfterEffects: [
        '¿Puedes ver si quebre algo?',
        'Apuesto a que duele',
        'Apuesto a que te dolió',
        'Espero no haber quebrado nada',
        'Espero que estés bien luego de eso',
        'Le atiné',
        'Creo que no funcionó',
        'Creo que no funcionó como esperaba',
        'Creo que no funcionó como quería',
        'Lo siento',
        'Lo siento si quebré algo',
        'Soy la mejor',
        'Soy la mejor hechicera',
        'Qué tonto',
        'Eso fue salvaje',
        'Eso fue monstruoso',
        'Eso fue fantástico',
        'Eso fue grandioso',
        'Eso fue impresionante',
        'Eso fue increible',
        'Eso fue bueno',
        'Eso fue stunning',
        'Eso fue estupefacto',
        'Eso fue sorprendente',
        'Eso fue maravilloso',
        'Eso me quitó el aliento',
      ],
    },
  },
};
