'use strict';

module.exports = {
  en: {
    translation: {
      Spell: {
        Launch: 'Here you go',
        Next: 'Ok',
        Previous: 'Ok, here\'s the previous spell',
        StartOver: 'Ok',
        Unhandled: 'I\'m sorry, I didn\'t understand what you said, was it maybe a new spell I don\'t know? ' +
          'I bet you don\'t know this one either',
        reprompt: 'Would you like to keep practicing?',

        CardTitle: 'Spell Practice',
      },

      Help: {
        ask: 'I love all kind of charms, curses and spells, but sometimes my magic wand doesn\'t work out well. ' +
          'Anyway, I can show you how to practice your spells, my specialty is the adavra kedabra, but don\'t worry, ' +
          'I am not able to even kill a fly. So, do you want to practice some spells with me?',
        reprompt: 'Do you want to practice some more spells?',
      },

      Exit: 'Goodbye, thanks for practicing. Til next time!',

      SuggestionChips: [
        'yes',
        'no',
      ],

      Interjections: [
        '<say-as interpret-as="interjection"> aw man </say-as>',
        '<say-as interpret-as="interjection"> bada bing bada boom </say-as>',
        '<say-as interpret-as="interjection"> bam </say-as>',
        '<say-as interpret-as="interjection"> bang </say-as>',
        '<say-as interpret-as="interjection"> bazinga </say-as>',
        '<say-as interpret-as="interjection"> beep beep </say-as>',
        '<say-as interpret-as="interjection"> bingo </say-as>',
        '<say-as interpret-as="interjection"> blarg </say-as>',
        '<say-as interpret-as="interjection"> blast </say-as>',
        '<say-as interpret-as="interjection"> boing </say-as>',
        '<say-as interpret-as="interjection"> boo </say-as>',
        '<say-as interpret-as="interjection"> boo hoo </say-as>',
        '<say-as interpret-as="interjection"> booya </say-as>',
        '<say-as interpret-as="interjection"> bravo </say-as>',
        '<say-as interpret-as="interjection"> bummer </say-as>',
        '<say-as interpret-as="interjection"> cha ching </say-as>',
        '<say-as interpret-as="interjection"> cheers </say-as>',
        '<say-as interpret-as="interjection"> choo choo </say-as>',
        '<say-as interpret-as="interjection"> cowabunga </say-as>',
        '<say-as interpret-as="interjection"> darn </say-as>',
        '<say-as interpret-as="interjection"> d’oh </say-as>',
        '<say-as interpret-as="interjection"> dun dun dun </say-as>',
        '<say-as interpret-as="interjection"> eek </say-as>',
        '<say-as interpret-as="interjection"> eureka </say-as>',
        '<say-as interpret-as="interjection"> fancy that </say-as>',
        '<say-as interpret-as="interjection"> geronimo </say-as>',
        '<say-as interpret-as="interjection"> kaboom </say-as>',
        '<say-as interpret-as="interjection"> kapow </say-as>',
        '<say-as interpret-as="interjection"> katchow </say-as>',
        '<say-as interpret-as="interjection"> kerbam </say-as>',
        '<say-as interpret-as="interjection"> kerboom </say-as>',
        '<say-as interpret-as="interjection"> kerpow </say-as>',
        '<say-as interpret-as="interjection"> kersplat </say-as>',
        '<say-as interpret-as="interjection"> look out </say-as>',
        '<say-as interpret-as="interjection"> mamma mia </say-as>',
        '<say-as interpret-as="interjection"> now now </say-as>',
        '<say-as interpret-as="interjection"> oh boy </say-as>',
        '<say-as interpret-as="interjection"> oh brother </say-as>',
        '<say-as interpret-as="interjection"> oh dear </say-as>',
        '<say-as interpret-as="interjection"> oh my </say-as>',
        '<say-as interpret-as="interjection"> oh snap </say-as>',
        '<say-as interpret-as="interjection"> oof </say-as>',
        '<say-as interpret-as="interjection"> ouch </say-as>',
        '<say-as interpret-as="interjection"> phew </say-as>',
        '<say-as interpret-as="interjection"> plop </say-as>',
        '<say-as interpret-as="interjection"> poof </say-as>',
        '<say-as interpret-as="interjection"> pow </say-as>',
        '<say-as interpret-as="interjection"> ta da </say-as>',
        '<say-as interpret-as="interjection"> uh oh </say-as>',
        '<say-as interpret-as="interjection"> wahoo </say-as>',
        '<say-as interpret-as="interjection"> wah wah </say-as>',
        '<say-as interpret-as="interjection"> whoops a daisy </say-as>',
        '<say-as interpret-as="interjection"> whoosh </say-as>',
        '<say-as interpret-as="interjection"> woo hoo </say-as>',
        '<say-as interpret-as="interjection"> wow </say-as>',
        '<say-as interpret-as="interjection"> wowza </say-as>',
        '<say-as interpret-as="interjection"> wowzer </say-as>',
        '<say-as interpret-as="interjection"> yikes </say-as>',
        '<say-as interpret-as="interjection"> zoinks </say-as>',
      ],

      AfterEffects: [
        'Can you see if I didn\'t break anything?',
        'I bet that hurt',
        'I bet that hurts',
        'I hope I didn\'t break anything',
        'I hope you are ok after that',
        'I nailed it',
        'I think that didn\'t work',
        'I think that didn\'t work out as expected',
        'I think that didn\'t work out as I wanted',
        'I\'m sorry',
        'I\'m sorry if I broke something',
        'I\'m the best',
        'I\'m the best charmer',
        'So silly',
        'That was amazing',
        'That was awesome',
        'That was breathtaking',
        'That was fantastic',
        'That was great',
        'That was impressive',
        'That was incredible',
        'That was ok',
        'That was stunning',
        'That was stupefying',
        'That was surprising',
        'That was wonderful',
      ],
    },
  },
};
