'use strict';

module.exports = [
  //  ALARMS
  'https://actions.google.com/sounds/v1/alarms/alarm_clock.ogg',
  'https://actions.google.com/sounds/v1/alarms/bugle_tune.ogg',
  //  ANIMALS
  'https://actions.google.com/sounds/v1/animals/animal_bark_and_growl.ogg',
  'https://actions.google.com/sounds/v1/animals/dog_growling.ogg',
  'https://actions.google.com/sounds/v1/animals/mouse_squeaking.ogg',
  //  CARTOON
  'https://actions.google.com/sounds/v1/cartoon/cartoon_boing.ogg',
  'https://actions.google.com/sounds/v1/cartoon/cartoon_cowbell.ogg',
  'https://actions.google.com/sounds/v1/cartoon/clang_and_wobble.ogg',
  'https://actions.google.com/sounds/v1/cartoon/concussive_guitar_hit.ogg',
  'https://actions.google.com/sounds/v1/cartoon/concussive_hit_guitar_boing.ogg',
  'https://actions.google.com/sounds/v1/cartoon/cowbell_ringing.ogg',
  'https://actions.google.com/sounds/v1/cartoon/deflate.ogg',
  'https://actions.google.com/sounds/v1/cartoon/fart_long_through_door.ogg',
  'https://actions.google.com/sounds/v1/cartoon/fart_toot.ogg',
  'https://actions.google.com/sounds/v1/cartoon/getting_stuck.ogg',
  'https://actions.google.com/sounds/v1/cartoon/goofy_spring_bounces.ogg',
  'https://actions.google.com/sounds/v1/cartoon/hair_ripping.ogg',
  'https://actions.google.com/sounds/v1/cartoon/long_fart.ogg',
  'https://actions.google.com/sounds/v1/cartoon/rubber_duck_squeak_series.ogg',
  'https://actions.google.com/sounds/v1/cartoon/rubber_glove_snapping_series.ogg',
  'https://actions.google.com/sounds/v1/cartoon/rubber_squeaking.ogg',
  'https://actions.google.com/sounds/v1/cartoon/siren_whistle.ogg',
  'https://actions.google.com/sounds/v1/cartoon/slide_whistle.ogg',
  'https://actions.google.com/sounds/v1/cartoon/slide_whistle_to_drum.ogg',
  'https://actions.google.com/sounds/v1/cartoon/tympani_bing.ogg',
  'https://actions.google.com/sounds/v1/cartoon/woodpecker.ogg',
  //  DOORS
  'https://actions.google.com/sounds/v1/doors/door_slams_fast_four_times.ogg',
  'https://actions.google.com/sounds/v1/doors/latch_opening_closing.ogg',
  'https://actions.google.com/sounds/v1/doors/lid_close_wood.ogg',
  'https://actions.google.com/sounds/v1/doors/medicine_cabinet_latch.ogg',
  'https://actions.google.com/sounds/v1/doors/metal_scrap_rattling.ogg',
  'https://actions.google.com/sounds/v1/doors/opening_closing_heavy_door.ogg',
  'https://actions.google.com/sounds/v1/doors/opening_door_with_key.ogg',
  'https://actions.google.com/sounds/v1/doors/screen_door_close.ogg',
  'https://actions.google.com/sounds/v1/doors/wood_door_open_close.ogg',
  'https://actions.google.com/sounds/v1/doors/wood_door_open.ogg',
  'https://actions.google.com/sounds/v1/doors/wood_rattle.ogg',
  //  EMERGENCY
  'https://actions.google.com/sounds/v1/emergency/emergency_radio_alert.ogg',
  'https://actions.google.com/sounds/v1/emergency/emergency_siren_short_burst.ogg',
  //  FOLEY
  'https://actions.google.com/sounds/v1/foley/body_in_car.ogg',
  'https://actions.google.com/sounds/v1/foley/change_drop_on_wood.ogg',
  'https://actions.google.com/sounds/v1/foley/dress_shoe_jog_on_gravel.ogg',
  'https://actions.google.com/sounds/v1/foley/dress_shoe_jog_on_wood.ogg',
  'https://actions.google.com/sounds/v1/foley/dress_shoe_run_on_concrete.ogg',
  'https://actions.google.com/sounds/v1/foley/dress_shoe_run_on_gravel.ogg',
  'https://actions.google.com/sounds/v1/foley/dress_shoe_run_on_wood.ogg',
  'https://actions.google.com/sounds/v1/foley/dress_shoe_walk_light_grit.ogg',
  'https://actions.google.com/sounds/v1/foley/dress_shoe_walk_solid_wood.ogg',
  'https://actions.google.com/sounds/v1/foley/dress_shoe_walking_down_stairs.ogg',
  'https://actions.google.com/sounds/v1/foley/dress_shoes_on_concrete_stairs.ogg',
  'https://actions.google.com/sounds/v1/foley/dress_shoes_on_stairs_concrete.ogg',
  'https://actions.google.com/sounds/v1/foley/dress_shoes_on_wood_stairs.ogg',
  'https://actions.google.com/sounds/v1/foley/dress_shoes_up_stairs_concrete.ogg',
  'https://actions.google.com/sounds/v1/foley/dress_shoes_up_stairs_wood.ogg',
  'https://actions.google.com/sounds/v1/foley/dress_shoe_jog_on_concrete.ogg',
  'https://actions.google.com/sounds/v1/foley/drink_and_swallow.ogg',
  'https://actions.google.com/sounds/v1/foley/dropping_object_in_bathroom.ogg',
  'https://actions.google.com/sounds/v1/foley/jog_down_concrete_stairs.ogg',
  'https://actions.google.com/sounds/v1/foley/jog_down_solid_wood_stairs.ogg',
  'https://actions.google.com/sounds/v1/foley/jog_on_grit.ogg',
  'https://actions.google.com/sounds/v1/foley/rake_swing_whoosh_close.ogg',
  //  HORROR
  'https://actions.google.com/sounds/v1/horror/aggressive_zombie_snarls.ogg',
  'https://actions.google.com/sounds/v1/horror/female_monster_attacking.ogg',
  'https://actions.google.com/sounds/v1/horror/female_monster_growls.ogg',
  'https://actions.google.com/sounds/v1/horror/meat_punch.ogg',
  'https://actions.google.com/sounds/v1/horror/monster_alien_growl_calm.ogg',
  'https://actions.google.com/sounds/v1/horror/monster_alien_growl_tense.ogg',
  'https://actions.google.com/sounds/v1/horror/monster_alien_grunt.ogg',
  'https://actions.google.com/sounds/v1/horror/monster_alien_grunt_hiss.ogg',
  'https://actions.google.com/sounds/v1/horror/synthetic_insects.ogg',
  //  HOUSEHOLD
  'https://actions.google.com/sounds/v1/household/bowl_spin.ogg',
  'https://actions.google.com/sounds/v1/household/glosing_old_window.ogg',
  'https://actions.google.com/sounds/v1/household/kitchen_noises.ogg',
  'https://actions.google.com/sounds/v1/household/phone_ringing.ogg',
  //  IMPACTS
  'https://actions.google.com/sounds/v1/impacts/crash.ogg',
  'https://actions.google.com/sounds/v1/impacts/crash_impact_sweetener.ogg',
  'https://actions.google.com/sounds/v1/impacts/crash_metal_sweetener_distant.ogg',
  'https://actions.google.com/sounds/v1/impacts/debris_hits.ogg',
  'https://actions.google.com/sounds/v1/impacts/dumpster.ogg',
  'https://actions.google.com/sounds/v1/impacts/dumpster_bottle_smash.ogg',
  'https://actions.google.com/sounds/v1/impacts/dumpster_rattle.ogg',
  'https://actions.google.com/sounds/v1/impacts/fridge_falls_leaks.ogg',
  'https://actions.google.com/sounds/v1/impacts/glass_pieces_on_metal.ogg',
  //  SCIENCE FICTION
  'https://actions.google.com/sounds/v1/science_fiction/dream_breath.ogg',
  //  WATER
  'https://actions.google.com/sounds/v1/water/air_woosh_underwater.ogg',
  //  WEAPONS
  'https://actions.google.com/sounds/v1/weapons/big_explosion_cut_off.ogg',
  'https://actions.google.com/sounds/v1/weapons/big_explosion_distant.ogg',
  'https://actions.google.com/sounds/v1/weapons/big_explosion_sweeping_in.ogg',
  'https://actions.google.com/sounds/v1/weapons/bullet_hit_car.ogg',
  'https://actions.google.com/sounds/v1/weapons/gun_drop_on_metal_grate.ogg',
  'https://actions.google.com/sounds/v1/weapons/gun_powder_ignite.ogg',
  'https://actions.google.com/sounds/v1/weapons/gun_shooting_cocking_foam.ogg',
  'https://actions.google.com/sounds/v1/weapons/gunshot_and_echo_long.ogg',
  'https://actions.google.com/sounds/v1/weapons/howitzer_cannon_fire.ogg',
  'https://actions.google.com/sounds/v1/weapons/lit_fuse.ogg',
  'https://actions.google.com/sounds/v1/weapons/machine_gun_hit_car.ogg',
  'https://actions.google.com/sounds/v1/weapons/rifle_cycle_far.ogg',
  'https://actions.google.com/sounds/v1/weapons/rifle_shot_echo.ogg',
  'https://actions.google.com/sounds/v1/weapons/metal_drop.ogg',
  //  WEATHER
  'https://actions.google.com/sounds/v1/weather/rolling_thunder.ogg',
  'https://actions.google.com/sounds/v1/weather/thunder_crack.ogg',
];
